version: '3.8'

services:
  be:
    build:
      context: ./be
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

  fe:
    build:
      context: ./fe
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env


    

  