# python , install dep and run the uvicorn server
FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "serve_models:app", "--host", "0.0.0.0", "--port", "8000", "--timeout-keep-alive", "90"]